### ISSUE TITLE
Possibility to use aliases

### ISSUE THREAD

**Issue by ps1x** [jderusse/docker-dns-gen#20]
Right now to make two domains i add two same images of apache with different service names in docker-compose.yml. Is there any other possibility to not spawn extra instances of apache?

Now:

```
version: "2"

services:
    host1:
        image: lordius/alpine-apache
        links:
           ......
    host2:
        image: lordius/alpine-apache
        links:
           ......
```
Wanted:
```
version:` "2"

services:
    host1:
        image: lordius/alpine-apache
        alias: host2
        alias: host3
        links:
           ......

```
